---
name: Run tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install -y clang libsubunit-dev check

      - name: Build
        run: |
          make

      - name: Test
        # Specifying the LDFLAGS is a workaround for issues with check on
        # Ubuntu
        run: |
          make LDFLAGS="`pkg-config --cflags --libs check`" test
